export const countryCategories = [
  { id: "OECD", label: "OECD" },
  { id: "EU", label: "EU" },
  { id: "ASEAN", label: "ASEAN" },
  { id: "G20", label: "G20" },
  { id: "G7", label: "G7" },
  { id: "BRICS", label: "BRICS" },
  { id: "NATO", label: "NATO" },
  { id: "Eurozone", label: "Eurozone" },
];

export const countryRegions = [
  { id: "Asia", label: "Asia" },
  { id: "Europe", label: "Europe" },
  { id: "Oceania", label: "Oceania" },
  { id: "Africa", label: "Africa" },
  { id: "North America", label: "North America" },
  { id: "South America", label: "South America" },
];

// Search-only aliases live in countrySearchAliases.js.
export const countries = [
  { code: "USA", name: "United States", englishDefiniteArticle: true, slug: "united-states", officialName: "United States of America", capitals: ["Washington D.C."], region: "North America", categories: ["G20", "G7", "NATO", "OECD"] },
  { code: "JPN", name: "Japan", slug: "japan", officialName: "Japan", capitals: ["Tokyo"], region: "Asia", categories: ["G20", "G7", "OECD"] },
  { code: "CHN", name: "China", slug: "china", officialName: "People's Republic of China", capitals: ["Beijing"], region: "Asia", categories: ["G20", "BRICS"] },
  { code: "TWN", name: "Taiwan", slug: "taiwan", officialName: "Republic of China", capitals: ["Taipei"], region: "Asia", categories: [] },
  { code: "HKG", name: "Hong Kong", slug: "hong-kong", officialName: "Hong Kong Special Administrative Region of the People's Republic of China", capitals: ["Hong Kong"], region: "Asia", categories: [] },
  { code: "MAC", name: "Macao", slug: "macao", officialName: "Macao Special Administrative Region of the People's Republic of China", capitals: ["Macao"], region: "Asia", categories: [] },
  { code: "DEU", name: "Germany", slug: "germany", officialName: "Federal Republic of Germany", capitals: ["Berlin"], region: "Europe", categories: ["G20", "EU", "NATO", "Eurozone", "G7", "OECD"] },
  { code: "FRA", name: "France", slug: "france", officialName: "French Republic", capitals: ["Paris"], region: "Europe", categories: ["G20", "EU", "NATO", "Eurozone", "G7", "OECD"] },
  { code: "GBR", name: "United Kingdom", englishDefiniteArticle: true, slug: "united-kingdom", officialName: "United Kingdom of Great Britain and Northern Ireland", capitals: ["London"], region: "Europe", categories: ["G20", "G7", "NATO", "OECD"] },
  { code: "ITA", name: "Italy", slug: "italy", officialName: "Italian Republic", capitals: ["Rome"], region: "Europe", categories: ["G20", "EU", "NATO", "Eurozone", "G7", "OECD"] },
  { code: "CAN", name: "Canada", slug: "canada", officialName: "Canada", capitals: ["Ottawa"], region: "North America", categories: ["G20", "G7", "NATO", "OECD"] },
  { code: "AUS", name: "Australia", slug: "australia", officialName: "Commonwealth of Australia", capitals: ["Canberra"], region: "Oceania", categories: ["G20", "OECD"] },
  { code: "NZL", name: "New Zealand", slug: "new-zealand", officialName: "New Zealand", capitals: ["Wellington"], region: "Oceania", categories: ["OECD"] },
  { code: "ASM", name: "American Samoa", slug: "american-samoa", officialName: "American Samoa", capitals: ["Pago Pago"], region: "Oceania", categories: [] },
  { code: "COK", name: "Cook Islands", slug: "cook-islands", officialName: "Cook Islands", capitals: ["Avarua"], region: "Oceania", categories: [] },
  { code: "FJI", name: "Fiji", slug: "fiji", officialName: "Republic of Fiji", capitals: ["Suva"], region: "Oceania", categories: [] },
  { code: "GUM", name: "Guam", slug: "guam", officialName: "Guam", capitals: ["Hagåtña"], region: "Oceania", categories: [] },
  { code: "MNP", name: "Northern Mariana Islands", slug: "northern-mariana-islands", officialName: "Commonwealth of the Northern Mariana Islands", capitals: ["Saipan"], region: "Oceania", categories: [] },
  { code: "NCL", name: "New Caledonia", slug: "new-caledonia", officialName: "New Caledonia", capitals: ["Nouméa"], region: "Oceania", categories: [] },
  { code: "NIU", name: "Niue", slug: "niue", officialName: "Niue", capitals: ["Alofi"], region: "Oceania", categories: [] },
  { code: "PCN", name: "Pitcairn", slug: "pitcairn", officialName: "Pitcairn, Henderson, Ducie and Oeno Islands", capitals: ["Adamstown"], region: "Oceania", categories: [] },
  { code: "PNG", name: "Papua New Guinea", slug: "papua-new-guinea", officialName: "Independent State of Papua New Guinea", capitals: ["Port Moresby"], region: "Oceania", categories: [] },
  { code: "PYF", name: "French Polynesia", slug: "french-polynesia", officialName: "French Polynesia", capitals: ["Papeetē"], region: "Oceania", categories: [] },
  { code: "SLB", name: "Solomon Islands", englishDefiniteArticle: true, slug: "solomon-islands", officialName: "Solomon Islands", capitals: ["Honiara"], region: "Oceania", categories: [] },
  { code: "TKL", name: "Tokelau", slug: "tokelau", officialName: "Tokelau", capitals: ["Nukunonu"], region: "Oceania", categories: [] },
  { code: "VUT", name: "Vanuatu", slug: "vanuatu", officialName: "Republic of Vanuatu", capitals: ["Port Vila"], region: "Oceania", categories: [] },
  { code: "FSM", name: "Federated States of Micronesia", englishDefiniteArticle: true, slug: "federated-states-of-micronesia", officialName: "Federated States of Micronesia", capitals: ["Palikir"], region: "Oceania", categories: [] },
  { code: "KIR", name: "Kiribati", slug: "kiribati", officialName: "Republic of Kiribati", capitals: ["South Tarawa"], region: "Oceania", categories: [] },
  { code: "MHL", name: "Marshall Islands", englishDefiniteArticle: true, slug: "marshall-islands", officialName: "Republic of the Marshall Islands", capitals: ["Majuro"], region: "Oceania", categories: [] },
  { code: "NRU", name: "Nauru", slug: "nauru", officialName: "Republic of Nauru", capitals: ["Yaren"], region: "Oceania", categories: [] },
  { code: "PLW", name: "Palau", slug: "palau", officialName: "Republic of Palau", capitals: ["Ngerulmud"], region: "Oceania", categories: [] },
  { code: "WSM", name: "Samoa", slug: "samoa", officialName: "Independent State of Samoa", capitals: ["Apia"], region: "Oceania", categories: [] },
  { code: "TON", name: "Tonga", slug: "tonga", officialName: "Kingdom of Tonga", capitals: ["Nuku'alofa"], region: "Oceania", categories: [] },
  { code: "TUV", name: "Tuvalu", slug: "tuvalu", officialName: "Tuvalu", capitals: ["Funafuti"], region: "Oceania", categories: [] },
  { code: "WLF", name: "Wallis and Futuna", slug: "wallis-and-futuna", officialName: "Territory of the Wallis and Futuna Islands", capitals: ["Mata-Utu"], region: "Oceania", categories: [] },
  { code: "KOR", name: "South Korea", slug: "south-korea", officialName: "Republic of Korea", capitals: ["Seoul"], region: "Asia", categories: ["G20", "OECD"] },
  { code: "PRK", name: "North Korea", slug: "north-korea", officialName: "Democratic People's Republic of Korea", capitals: ["Pyongyang"], region: "Asia", categories: [] },
  { code: "IDN", name: "Indonesia", slug: "indonesia", officialName: "Republic of Indonesia", capitals: ["Jakarta"], region: "Asia", categories: ["G20", "ASEAN", "BRICS"] },
  { code: "TUR", name: "Türkiye", slug: "turkiye", officialName: "Republic of Türkiye", capitals: ["Ankara"], region: "Asia", categories: ["G20", "NATO", "OECD"] },
  { code: "IND", name: "India", slug: "india", officialName: "Republic of India", capitals: ["New Delhi"], region: "Asia", categories: ["G20", "BRICS"] },
  { code: "LKA", name: "Sri Lanka", slug: "sri-lanka", officialName: "Democratic Socialist Republic of Sri Lanka", capitals: ["Sri Jayawardenepura Kotte", "Colombo"], region: "Asia", categories: [] },
  { code: "MDV", name: "Maldives", englishDefiniteArticle: true, slug: "maldives", officialName: "Republic of Maldives", capitals: ["Malé"], region: "Asia", categories: [] },
  { code: "BGD", name: "Bangladesh", slug: "bangladesh", officialName: "People's Republic of Bangladesh", capitals: ["Dhaka"], region: "Asia", categories: [] },
  { code: "BTN", name: "Bhutan", slug: "bhutan", officialName: "Kingdom of Bhutan", capitals: ["Thimphu"], region: "Asia", categories: [] },
  { code: "NPL", name: "Nepal", slug: "nepal", officialName: "Federal Democratic Republic of Nepal", capitals: ["Kathmandu"], region: "Asia", categories: [] },
  { code: "PAK", name: "Pakistan", slug: "pakistan", officialName: "Islamic Republic of Pakistan", capitals: ["Islamabad"], region: "Asia", categories: [] },
  { code: "AFG", name: "Afghanistan", slug: "afghanistan", officialName: "Islamic Republic of Afghanistan", capitals: ["Kabul"], region: "Asia", categories: [] },
  { code: "TJK", name: "Tajikistan", slug: "tajikistan", officialName: "Republic of Tajikistan", capitals: ["Dushanbe"], region: "Asia", categories: [] },
  { code: "KGZ", name: "Kyrgyzstan", slug: "kyrgyzstan", officialName: "Kyrgyz Republic", capitals: ["Bishkek"], region: "Asia", categories: [] },
  { code: "TKM", name: "Turkmenistan", slug: "turkmenistan", officialName: "Turkmenistan", capitals: ["Ashgabat"], region: "Asia", categories: [] },
  { code: "UZB", name: "Uzbekistan", slug: "uzbekistan", officialName: "Republic of Uzbekistan", capitals: ["Tashkent"], region: "Asia", categories: [] },
  { code: "KAZ", name: "Kazakhstan", slug: "kazakhstan", officialName: "Republic of Kazakhstan", capitals: ["Astana"], region: "Asia", categories: [] },
  { code: "MNG", name: "Mongolia", slug: "mongolia", officialName: "Mongolia", capitals: ["Ulaanbaatar"], region: "Asia", categories: [] },
  { code: "AZE", name: "Azerbaijan", slug: "azerbaijan", officialName: "Republic of Azerbaijan", capitals: ["Baku"], region: "Asia", categories: [] },
  { code: "GEO", name: "Georgia", slug: "georgia", officialName: "Georgia", capitals: ["Tbilisi"], region: "Asia", categories: [] },
  { code: "ARM", name: "Armenia", slug: "armenia", officialName: "Republic of Armenia", capitals: ["Yerevan"], region: "Asia", categories: [] },
  { code: "SAU", name: "Saudi Arabia", slug: "saudi-arabia", officialName: "Kingdom of Saudi Arabia", capitals: ["Riyadh"], region: "Asia", categories: ["G20", "BRICS", "GCC"] },
  { code: "IRN", name: "Iran", slug: "iran", officialName: "Islamic Republic of Iran", capitals: ["Tehran"], region: "Asia", categories: ["BRICS"] },
  { code: "IRQ", name: "Iraq", slug: "iraq", officialName: "Republic of Iraq", capitals: ["Baghdad"], region: "Asia", categories: [] },
  { code: "SYR", name: "Syria", slug: "syria", officialName: "Syrian Arab Republic", capitals: ["Damascus"], region: "Asia", categories: [] },
  { code: "LBN", name: "Lebanon", slug: "lebanon", officialName: "Lebanese Republic", capitals: ["Beirut"], region: "Asia", categories: [] },
  { code: "JOR", name: "Jordan", slug: "jordan", officialName: "Hashemite Kingdom of Jordan", capitals: ["Amman"], region: "Asia", categories: [] },
  { code: "KWT", name: "Kuwait", slug: "kuwait", officialName: "State of Kuwait", capitals: ["Kuwait City"], region: "Asia", categories: ["GCC"] },
  { code: "BHR", name: "Bahrain", slug: "bahrain", officialName: "Kingdom of Bahrain", capitals: ["Manama"], region: "Asia", categories: ["GCC"] },
  { code: "QAT", name: "Qatar", slug: "qatar", officialName: "State of Qatar", capitals: ["Doha"], region: "Asia", categories: ["GCC"] },
  { code: "ARE", name: "United Arab Emirates", englishDefiniteArticle: true, slug: "united-arab-emirates", officialName: "United Arab Emirates", capitals: ["Abu Dhabi"], region: "Asia", categories: ["BRICS", "GCC"] },
  { code: "OMN", name: "Oman", slug: "oman", officialName: "Sultanate of Oman", capitals: ["Muscat"], region: "Asia", categories: ["GCC"] },
  { code: "YEM", name: "Yemen", slug: "yemen", officialName: "Republic of Yemen", capitals: ["Sana'a"], region: "Asia", categories: [] },
  { code: "ARG", name: "Argentina", slug: "argentina", officialName: "Argentine Republic", capitals: ["Buenos Aires"], region: "South America", categories: ["G20"] },
  { code: "BRA", name: "Brazil", slug: "brazil", officialName: "Federative Republic of Brazil", capitals: ["Brasília"], region: "South America", categories: ["G20", "BRICS"] },
  { code: "MEX", name: "Mexico", slug: "mexico", officialName: "United Mexican States", capitals: ["Mexico City"], region: "North America", categories: ["G20", "OECD"] },
  { code: "ABW", name: "Aruba", slug: "aruba", officialName: "Country of Aruba", capitals: ["Oranjestad"], region: "North America", categories: [] },
  { code: "AIA", name: "Anguilla", slug: "anguilla", officialName: "Anguilla", capitals: ["The Valley"], region: "North America", categories: [] },
  { code: "BMU", name: "Bermuda", slug: "bermuda", officialName: "Bermuda Islands", capitals: ["Hamilton"], region: "North America", categories: ["NATO"] },
  { code: "GTM", name: "Guatemala", slug: "guatemala", officialName: "Republic of Guatemala", capitals: ["Guatemala City"], region: "North America", categories: [] },
  { code: "BLZ", name: "Belize", slug: "belize", officialName: "Belize", capitals: ["Belmopan"], region: "North America", categories: [] },
  { code: "SLV", name: "El Salvador", slug: "el-salvador", officialName: "Republic of El Salvador", capitals: ["San Salvador"], region: "North America", categories: [] },
  { code: "HND", name: "Honduras", slug: "honduras", officialName: "Republic of Honduras", capitals: ["Tegucigalpa"], region: "North America", categories: [] },
  { code: "NIC", name: "Nicaragua", slug: "nicaragua", officialName: "Republic of Nicaragua", capitals: ["Managua"], region: "North America", categories: [] },
  { code: "PAN", name: "Panama", slug: "panama", officialName: "Republic of Panama", capitals: ["Panama City"], region: "North America", categories: [] },
  { code: "BHS", name: "Bahamas", englishDefiniteArticle: true, slug: "bahamas", officialName: "Commonwealth of The Bahamas", capitals: ["Nassau"], region: "North America", categories: [] },
  { code: "CUB", name: "Cuba", slug: "cuba", officialName: "Republic of Cuba", capitals: ["Havana"], region: "North America", categories: [] },
  { code: "JAM", name: "Jamaica", slug: "jamaica", officialName: "Jamaica", capitals: ["Kingston"], region: "North America", categories: [] },
  { code: "HTI", name: "Haiti", slug: "haiti", officialName: "Republic of Haiti", capitals: ["Port-au-Prince"], region: "North America", categories: [] },
  { code: "DOM", name: "Dominican Republic", englishDefiniteArticle: true, slug: "dominican-republic", officialName: "Dominican Republic", capitals: ["Santo Domingo"], region: "North America", categories: [] },
  { code: "ATG", name: "Antigua and Barbuda", slug: "antigua-and-barbuda", officialName: "Antigua and Barbuda", capitals: ["Saint John's"], region: "North America", categories: [] },
  { code: "KNA", name: "Saint Kitts and Nevis", slug: "saint-kitts-and-nevis", officialName: "Federation of Saint Christopher and Nevis", capitals: ["Basseterre"], region: "North America", categories: [] },
  { code: "DMA", name: "Dominica", slug: "dominica", officialName: "Commonwealth of Dominica", capitals: ["Roseau"], region: "North America", categories: [] },
  { code: "LCA", name: "Saint Lucia", slug: "saint-lucia", officialName: "Saint Lucia", capitals: ["Castries"], region: "North America", categories: [] },
  { code: "BRB", name: "Barbados", slug: "barbados", officialName: "Barbados", capitals: ["Bridgetown"], region: "North America", categories: [] },
  { code: "VCT", name: "Saint Vincent and the Grenadines", slug: "saint-vincent-and-the-grenadines", officialName: "Saint Vincent and the Grenadines", capitals: ["Kingstown"], region: "North America", categories: [] },
  { code: "GRD", name: "Grenada", slug: "grenada", officialName: "Grenada", capitals: ["St. George's"], region: "North America", categories: [] },
  { code: "TTO", name: "Trinidad and Tobago", slug: "trinidad-and-tobago", officialName: "Republic of Trinidad and Tobago", capitals: ["Port of Spain"], region: "North America", categories: [] },
  { code: "CYM", name: "Cayman Islands", slug: "cayman-islands", officialName: "Cayman Islands", capitals: ["George Town"], region: "North America", categories: [] },
  { code: "CUW", name: "Curaçao", slug: "curacao", officialName: "Country of Curaçao", capitals: ["Willemstad"], region: "North America", categories: [] },
  { code: "GLP", name: "Guadeloupe", slug: "guadeloupe", officialName: "Guadeloupe", capitals: ["Basse-Terre"], region: "North America", categories: ["EU", "Eurozone"] },
  { code: "GRL", name: "Greenland", slug: "greenland", officialName: "Greenland", capitals: ["Nuuk"], region: "North America", categories: ["NATO"] },
  { code: "MAF", name: "Saint Martin", slug: "saint-martin", officialName: "Collectivity of Saint Martin", capitals: ["Marigot"], region: "North America", categories: ["EU", "Eurozone"] },
  { code: "MSR", name: "Montserrat", slug: "montserrat", officialName: "Montserrat", capitals: ["Brades"], region: "North America", categories: [] },
  { code: "MTQ", name: "Martinique", slug: "martinique", officialName: "Territorial Collectivity of Martinique", capitals: ["Fort-de-France"], region: "North America", categories: ["EU", "Eurozone"] },
  { code: "PRI", name: "Puerto Rico", slug: "puerto-rico", officialName: "Commonwealth of Puerto Rico", capitals: ["San Juan"], region: "North America", categories: [] },
  { code: "SPM", name: "Saint Pierre and Miquelon", slug: "saint-pierre-and-miquelon", officialName: "Territorial Collectivity of Saint Pierre and Miquelon", capitals: ["Saint-Pierre"], region: "North America", categories: ["NATO", "Eurozone"] },
  { code: "SXM", name: "Sint Maarten", slug: "sint-maarten", officialName: "Sint Maarten", capitals: ["Philipsburg"], region: "North America", categories: [] },
  { code: "TCA", name: "Turks and Caicos Islands", slug: "turks-and-caicos-islands", officialName: "Turks and Caicos Islands", capitals: ["Cockburn Town"], region: "North America", categories: [] },
  { code: "VGB", name: "British Virgin Islands", slug: "british-virgin-islands", officialName: "Virgin Islands", capitals: ["Road Town"], region: "North America", categories: [] },
  { code: "VIR", name: "U.S. Virgin Islands", slug: "us-virgin-islands", officialName: "Virgin Islands of the United States", capitals: ["Charlotte Amalie"], region: "North America", categories: [] },
  { code: "VEN", name: "Venezuela", slug: "venezuela", officialName: "Bolivarian Republic of Venezuela", capitals: ["Caracas"], region: "South America", categories: [] },
  { code: "FLK", name: "Falkland Islands", slug: "falkland-islands", officialName: "Falkland Islands", capitals: ["Stanley"], region: "South America", categories: [] },
  { code: "GUF", name: "French Guiana", slug: "french-guiana", officialName: "French Guiana", capitals: ["Cayenne"], region: "South America", categories: ["EU", "Eurozone"] },
  { code: "GUY", name: "Guyana", slug: "guyana", officialName: "Co-operative Republic of Guyana", capitals: ["Georgetown"], region: "South America", categories: [] },
  { code: "SUR", name: "Suriname", slug: "suriname", officialName: "Republic of Suriname", capitals: ["Paramaribo"], region: "South America", categories: [] },
  { code: "ECU", name: "Ecuador", slug: "ecuador", officialName: "Republic of Ecuador", capitals: ["Quito"], region: "South America", categories: [] },
  { code: "BOL", name: "Bolivia", slug: "bolivia", officialName: "Plurinational State of Bolivia", capitals: ["Sucre"], region: "South America", categories: [] },
  { code: "PRY", name: "Paraguay", slug: "paraguay", officialName: "Republic of Paraguay", capitals: ["Asunción"], region: "South America", categories: [] },
  { code: "URY", name: "Uruguay", slug: "uruguay", officialName: "Oriental Republic of Uruguay", capitals: ["Montevideo"], region: "South America", categories: [] },
  { code: "PER", name: "Peru", slug: "peru", officialName: "Republic of Peru", capitals: ["Lima"], region: "South America", categories: [] },
  { code: "RUS", name: "Russia", slug: "russia", officialName: "Russian Federation", capitals: ["Moscow"], region: "Europe", categories: ["G20", "BRICS"] },
  { code: "ZAF", name: "South Africa", slug: "south-africa", officialName: "Republic of South Africa", capitals: ["Pretoria", "Cape Town", "Bloemfontein"], region: "Africa", categories: ["G20", "AU", "BRICS"] },
  { code: "CHL", name: "Chile", slug: "chile", officialName: "Republic of Chile", capitals: ["Santiago"], region: "South America", categories: ["OECD"] },
  { code: "COL", name: "Colombia", slug: "colombia", officialName: "Republic of Colombia", capitals: ["Bogotá"], region: "South America", categories: ["OECD"] },
  { code: "CRI", name: "Costa Rica", slug: "costa-rica", officialName: "Republic of Costa Rica", capitals: ["San José"], region: "North America", categories: ["OECD"] },
  { code: "NOR", name: "Norway", slug: "norway", officialName: "Kingdom of Norway", capitals: ["Oslo"], region: "Europe", categories: ["NATO", "OECD"] },
  { code: "ISL", name: "Iceland", slug: "iceland", officialName: "Iceland", capitals: ["Reykjavik"], region: "Europe", categories: ["NATO", "OECD"] },
  { code: "CHE", name: "Switzerland", slug: "switzerland", officialName: "Swiss Confederation", capitals: ["Bern"], region: "Europe", categories: ["OECD"] },
  { code: "ISR", name: "Israel", slug: "israel", officialName: "State of Israel", capitals: ["Jerusalem"], region: "Asia", categories: ["OECD"] },
  { code: "FRO", name: "Faroe Islands", slug: "faroe-islands", officialName: "Faroe Islands", capitals: ["Tórshavn"], region: "Europe", categories: ["NATO"] },
  { code: "GIB", name: "Gibraltar", slug: "gibraltar", officialName: "Gibraltar", capitals: ["Gibraltar"], region: "Europe", categories: ["NATO"] },
  { code: "IMN", name: "Isle of Man", slug: "isle-of-man", officialName: "Isle of Man", capitals: ["Douglas"], region: "Europe", categories: ["NATO"] },
  { code: "LIE", name: "Liechtenstein", slug: "liechtenstein", officialName: "Principality of Liechtenstein", capitals: ["Vaduz"], region: "Europe", categories: [] },
  { code: "VAT", name: "Vatican City", slug: "vatican-city", officialName: "Vatican City State", capitals: ["Vatican City"], region: "Europe", categories: [] },
  { code: "SMR", name: "San Marino", slug: "san-marino", officialName: "Republic of San Marino", capitals: ["City of San Marino"], region: "Europe", categories: [] },
  { code: "AND", name: "Andorra", slug: "andorra", officialName: "Principality of Andorra", capitals: ["Andorra la Vella"], region: "Europe", categories: [] },
  { code: "MCO", name: "Monaco", slug: "monaco", officialName: "Principality of Monaco", capitals: ["Monaco"], region: "Europe", categories: [] },
  { code: "BLR", name: "Belarus", slug: "belarus", officialName: "Republic of Belarus", capitals: ["Minsk"], region: "Europe", categories: [] },
  { code: "BIH", name: "Bosnia and Herzegovina", slug: "bosnia-and-herzegovina", officialName: "Bosnia and Herzegovina", capitals: ["Sarajevo"], region: "Europe", categories: [] },
  { code: "SRB", name: "Serbia", slug: "serbia", officialName: "Republic of Serbia", capitals: ["Belgrade"], region: "Europe", categories: [] },
  { code: "MNE", name: "Montenegro", slug: "montenegro", officialName: "Montenegro", capitals: ["Podgorica"], region: "Europe", categories: ["NATO"] },
  { code: "KOS", name: "Kosovo", slug: "kosovo", officialName: "Republic of Kosovo", capitals: ["Pristina"], region: "Europe", categories: [] },
  { code: "MKD", name: "North Macedonia", slug: "north-macedonia", officialName: "Republic of North Macedonia", capitals: ["Skopje"], region: "Europe", categories: ["NATO"] },
  { code: "ALB", name: "Albania", slug: "albania", officialName: "Republic of Albania", capitals: ["Tirana"], region: "Europe", categories: ["NATO"] },
  { code: "MDA", name: "Moldova", slug: "moldova", officialName: "Republic of Moldova", capitals: ["Chișinău"], region: "Europe", categories: [] },
  { code: "UKR", name: "Ukraine", slug: "ukraine", officialName: "Ukraine", capitals: ["Kyiv"], region: "Europe", categories: [] },
  { code: "AUT", name: "Austria", slug: "austria", officialName: "Republic of Austria", capitals: ["Vienna"], region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "BEL", name: "Belgium", slug: "belgium", officialName: "Kingdom of Belgium", capitals: ["Brussels"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "BGR", name: "Bulgaria", slug: "bulgaria", officialName: "Republic of Bulgaria", capitals: ["Sofia"], region: "Europe", categories: ["EU", "NATO", "Eurozone"] },
  { code: "HRV", name: "Croatia", slug: "croatia", officialName: "Republic of Croatia", capitals: ["Zagreb"], region: "Europe", categories: ["EU", "NATO", "Eurozone"] },
  { code: "CYP", name: "Cyprus", slug: "cyprus", officialName: "Republic of Cyprus", capitals: ["Nicosia"], region: "Asia", categories: ["EU", "Eurozone"] },
  { code: "CZE", name: "Czechia", slug: "czechia", officialName: "Czech Republic", capitals: ["Prague"], region: "Europe", categories: ["EU", "NATO", "OECD"] },
  { code: "DNK", name: "Denmark", slug: "denmark", officialName: "Kingdom of Denmark", capitals: ["Copenhagen"], region: "Europe", categories: ["EU", "NATO", "OECD"] },
  { code: "EST", name: "Estonia", slug: "estonia", officialName: "Republic of Estonia", capitals: ["Tallinn"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "FIN", name: "Finland", slug: "finland", officialName: "Republic of Finland", capitals: ["Helsinki"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "GRC", name: "Greece", slug: "greece", officialName: "Hellenic Republic", capitals: ["Athens"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "HUN", name: "Hungary", slug: "hungary", officialName: "Hungary", capitals: ["Budapest"], region: "Europe", categories: ["EU", "NATO", "OECD"] },
  { code: "IRL", name: "Ireland", slug: "ireland", officialName: "Ireland", capitals: ["Dublin"], region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "LVA", name: "Latvia", slug: "latvia", officialName: "Republic of Latvia", capitals: ["Riga"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "LTU", name: "Lithuania", slug: "lithuania", officialName: "Republic of Lithuania", capitals: ["Vilnius"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "LUX", name: "Luxembourg", slug: "luxembourg", officialName: "Grand Duchy of Luxembourg", capitals: ["Luxembourg"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "MLT", name: "Malta", slug: "malta", officialName: "Republic of Malta", capitals: ["Valletta"], region: "Europe", categories: ["EU", "Eurozone"] },
  { code: "NLD", name: "Netherlands", englishDefiniteArticle: true, slug: "netherlands", officialName: "Kingdom of the Netherlands", capitals: ["Amsterdam"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "POL", name: "Poland", slug: "poland", officialName: "Republic of Poland", capitals: ["Warsaw"], region: "Europe", categories: ["EU", "NATO", "OECD"] },
  { code: "PRT", name: "Portugal", slug: "portugal", officialName: "Portuguese Republic", capitals: ["Lisbon"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "ROU", name: "Romania", slug: "romania", officialName: "Romania", capitals: ["Bucharest"], region: "Europe", categories: ["EU", "NATO"] },
  { code: "SVK", name: "Slovakia", slug: "slovakia", officialName: "Slovak Republic", capitals: ["Bratislava"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "SVN", name: "Slovenia", slug: "slovenia", officialName: "Republic of Slovenia", capitals: ["Ljubljana"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "ESP", name: "Spain", slug: "spain", officialName: "Kingdom of Spain", capitals: ["Madrid"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "SWE", name: "Sweden", slug: "sweden", officialName: "Kingdom of Sweden", capitals: ["Stockholm"], region: "Europe", categories: ["EU", "NATO", "OECD"] },
  { code: "BRN", name: "Brunei", slug: "brunei", officialName: "Brunei Darussalam", capitals: ["Bandar Seri Begawan"], region: "Asia", categories: ["ASEAN"] },
  { code: "KHM", name: "Cambodia", slug: "cambodia", officialName: "Kingdom of Cambodia", capitals: ["Phnom Penh"], region: "Asia", categories: ["ASEAN"] },
  { code: "LAO", name: "Laos", slug: "laos", officialName: "Lao People's Democratic Republic", capitals: ["Vientiane"], region: "Asia", categories: ["ASEAN"] },
  { code: "MYS", name: "Malaysia", slug: "malaysia", officialName: "Malaysia", capitals: ["Kuala Lumpur"], region: "Asia", categories: ["ASEAN"] },
  { code: "MMR", name: "Myanmar", slug: "myanmar", officialName: "Republic of the Union of Myanmar", capitals: ["Naypyidaw"], region: "Asia", categories: ["ASEAN"] },
  { code: "PHL", name: "Philippines", englishDefiniteArticle: true, slug: "philippines", officialName: "Republic of the Philippines", capitals: ["Manila"], region: "Asia", categories: ["ASEAN"] },
  { code: "SGP", name: "Singapore", slug: "singapore", officialName: "Republic of Singapore", capitals: ["Singapore"], region: "Asia", categories: ["ASEAN"] },
  { code: "THA", name: "Thailand", slug: "thailand", officialName: "Kingdom of Thailand", capitals: ["Bangkok"], region: "Asia", categories: ["ASEAN"] },
  { code: "TLS", name: "Timor-Leste", slug: "timor-leste", officialName: "Democratic Republic of Timor-Leste", capitals: ["Dili"], region: "Asia", categories: ["ASEAN"] },
  { code: "VNM", name: "Vietnam", slug: "vietnam", officialName: "Socialist Republic of Viet Nam", capitals: ["Hanoi"], region: "Asia", categories: ["ASEAN"] },
  { code: "WBG", name: "Palestine", slug: "palestine", officialName: "State of Palestine", capitals: ["Ramallah"], region: "Asia", categories: [] },
  { code: "DZA", name: "Algeria", slug: "algeria", officialName: "People's Democratic Republic of Algeria", capitals: ["Algiers"], region: "Africa", categories: ["AU"] },
  { code: "AGO", name: "Angola", slug: "angola", officialName: "Republic of Angola", capitals: ["Luanda"], region: "Africa", categories: ["AU"] },
  { code: "BEN", name: "Benin", slug: "benin", officialName: "Republic of Benin", capitals: ["Porto-Novo"], region: "Africa", categories: ["AU"] },
  { code: "BWA", name: "Botswana", slug: "botswana", officialName: "Republic of Botswana", capitals: ["Gaborone"], region: "Africa", categories: ["AU"] },
  { code: "BFA", name: "Burkina Faso", slug: "burkina-faso", officialName: "Burkina Faso", capitals: ["Ouagadougou"], region: "Africa", categories: ["AU"] },
  { code: "BDI", name: "Burundi", slug: "burundi", officialName: "Republic of Burundi", capitals: ["Gitega"], region: "Africa", categories: ["AU"] },
  { code: "CPV", name: "Cabo Verde", slug: "cabo-verde", officialName: "Republic of Cabo Verde", capitals: ["Praia"], region: "Africa", categories: ["AU"] },
  { code: "CMR", name: "Cameroon", slug: "cameroon", officialName: "Republic of Cameroon", capitals: ["Yaoundé"], region: "Africa", categories: ["AU"] },
  { code: "CAF", name: "Central African Republic", englishDefiniteArticle: true, slug: "central-african-republic", officialName: "Central African Republic", capitals: ["Bangui"], region: "Africa", categories: ["AU"] },
  { code: "TCD", name: "Chad", slug: "chad", officialName: "Republic of Chad", capitals: ["N'Djamena"], region: "Africa", categories: ["AU"] },
  { code: "COM", name: "Comoros", slug: "comoros", officialName: "Union of the Comoros", capitals: ["Moroni"], region: "Africa", categories: ["AU"] },
  { code: "COG", name: "Republic of the Congo", englishDefiniteArticle: true, slug: "republic-of-the-congo", officialName: "Republic of the Congo", capitals: ["Brazzaville"], region: "Africa", categories: ["AU"] },
  { code: "COD", name: "DR Congo", slug: "dr-congo", officialName: "Democratic Republic of the Congo", capitals: ["Kinshasa"], region: "Africa", categories: ["AU"] },
  { code: "CIV", name: "Côte d’Ivoire", slug: "cote-divoire", officialName: "Republic of Côte d'Ivoire", capitals: ["Yamoussoukro"], region: "Africa", categories: ["AU"] },
  { code: "DJI", name: "Djibouti", slug: "djibouti", officialName: "Republic of Djibouti", capitals: ["Djibouti"], region: "Africa", categories: ["AU"] },
  { code: "EGY", name: "Egypt", slug: "egypt", officialName: "Arab Republic of Egypt", capitals: ["Cairo"], region: "Africa", categories: ["AU", "BRICS"] },
  { code: "GNQ", name: "Equatorial Guinea", slug: "equatorial-guinea", officialName: "Republic of Equatorial Guinea", capitals: ["Malabo"], region: "Africa", categories: ["AU"] },
  { code: "ERI", name: "Eritrea", slug: "eritrea", officialName: "State of Eritrea", capitals: ["Asmara"], region: "Africa", categories: ["AU"] },
  { code: "SWZ", name: "Eswatini", slug: "eswatini", officialName: "Kingdom of Eswatini", capitals: ["Mbabane", "Lobamba"], region: "Africa", categories: ["AU"] },
  { code: "ETH", name: "Ethiopia", slug: "ethiopia", officialName: "Federal Democratic Republic of Ethiopia", capitals: ["Addis Ababa"], region: "Africa", categories: ["AU", "BRICS"] },
  { code: "GAB", name: "Gabon", slug: "gabon", officialName: "Gabonese Republic", capitals: ["Libreville"], region: "Africa", categories: ["AU"] },
  { code: "GMB", name: "Gambia", englishDefiniteArticle: true, slug: "gambia", officialName: "Republic of The Gambia", capitals: ["Banjul"], region: "Africa", categories: ["AU"] },
  { code: "GHA", name: "Ghana", slug: "ghana", officialName: "Republic of Ghana", capitals: ["Accra"], region: "Africa", categories: ["AU"] },
  { code: "GIN", name: "Guinea", slug: "guinea", officialName: "Republic of Guinea", capitals: ["Conakry"], region: "Africa", categories: ["AU"] },
  { code: "GNB", name: "Guinea-Bissau", slug: "guinea-bissau", officialName: "Republic of Guinea-Bissau", capitals: ["Bissau"], region: "Africa", categories: ["AU"] },
  { code: "KEN", name: "Kenya", slug: "kenya", officialName: "Republic of Kenya", capitals: ["Nairobi"], region: "Africa", categories: ["AU"] },
  { code: "LSO", name: "Lesotho", slug: "lesotho", officialName: "Kingdom of Lesotho", capitals: ["Maseru"], region: "Africa", categories: ["AU"] },
  { code: "LBR", name: "Liberia", slug: "liberia", officialName: "Republic of Liberia", capitals: ["Monrovia"], region: "Africa", categories: ["AU"] },
  { code: "LBY", name: "Libya", slug: "libya", officialName: "State of Libya", capitals: ["Tripoli"], region: "Africa", categories: ["AU"] },
  { code: "MDG", name: "Madagascar", slug: "madagascar", officialName: "Republic of Madagascar", capitals: ["Antananarivo"], region: "Africa", categories: ["AU"] },
  { code: "MWI", name: "Malawi", slug: "malawi", officialName: "Republic of Malawi", capitals: ["Lilongwe"], region: "Africa", categories: ["AU"] },
  { code: "MYT", name: "Mayotte", slug: "mayotte", officialName: "Department of Mayotte", capitals: ["Mamoudzou"], region: "Africa", categories: ["EU", "Eurozone"] },
  { code: "MLI", name: "Mali", slug: "mali", officialName: "Republic of Mali", capitals: ["Bamako"], region: "Africa", categories: ["AU"] },
  { code: "MRT", name: "Mauritania", slug: "mauritania", officialName: "Islamic Republic of Mauritania", capitals: ["Nouakchott"], region: "Africa", categories: ["AU"] },
  { code: "MUS", name: "Mauritius", slug: "mauritius", officialName: "Republic of Mauritius", capitals: ["Port Louis"], region: "Africa", categories: ["AU"] },
  { code: "MAR", name: "Morocco", slug: "morocco", officialName: "Kingdom of Morocco", capitals: ["Rabat"], region: "Africa", categories: ["AU"] },
  { code: "MOZ", name: "Mozambique", slug: "mozambique", officialName: "Republic of Mozambique", capitals: ["Maputo"], region: "Africa", categories: ["AU"] },
  { code: "NAM", name: "Namibia", slug: "namibia", officialName: "Republic of Namibia", capitals: ["Windhoek"], region: "Africa", categories: ["AU"] },
  { code: "NER", name: "Niger", slug: "niger", officialName: "Republic of the Niger", capitals: ["Niamey"], region: "Africa", categories: ["AU"] },
  { code: "NGA", name: "Nigeria", slug: "nigeria", officialName: "Federal Republic of Nigeria", capitals: ["Abuja"], region: "Africa", categories: ["AU"] },
  { code: "RWA", name: "Rwanda", slug: "rwanda", officialName: "Republic of Rwanda", capitals: ["Kigali"], region: "Africa", categories: ["AU"] },
  { code: "REU", name: "Réunion", slug: "reunion", officialName: "Réunion", capitals: ["Saint-Denis"], region: "Africa", categories: ["EU", "Eurozone"] },
  { code: "SHN", name: "Saint Helena", slug: "saint-helena", officialName: "Saint Helena", capitals: ["Jamestown"], region: "Africa", categories: [] },
  { code: "STP", name: "São Tomé and Príncipe", slug: "sao-tome-and-principe", officialName: "Democratic Republic of Sao Tome and Principe", capitals: ["São Tomé"], region: "Africa", categories: ["AU"] },
  { code: "SEN", name: "Senegal", slug: "senegal", officialName: "Republic of Senegal", capitals: ["Dakar"], region: "Africa", categories: ["AU"] },
  { code: "SYC", name: "Seychelles", slug: "seychelles", officialName: "Republic of Seychelles", capitals: ["Victoria"], region: "Africa", categories: ["AU"] },
  { code: "SLE", name: "Sierra Leone", slug: "sierra-leone", officialName: "Republic of Sierra Leone", capitals: ["Freetown"], region: "Africa", categories: ["AU"] },
  { code: "SOM", name: "Somalia", slug: "somalia", officialName: "Federal Republic of Somalia", capitals: ["Mogadishu"], region: "Africa", categories: ["AU"] },
  { code: "SSD", name: "South Sudan", slug: "south-sudan", officialName: "Republic of South Sudan", capitals: ["Juba"], region: "Africa", categories: ["AU"] },
  { code: "SDN", name: "Sudan", slug: "sudan", officialName: "Republic of the Sudan", capitals: ["Khartoum"], region: "Africa", categories: ["AU"] },
  { code: "TZA", name: "Tanzania", slug: "tanzania", officialName: "United Republic of Tanzania", capitals: ["Dodoma"], region: "Africa", categories: ["AU"] },
  { code: "TGO", name: "Togo", slug: "togo", officialName: "Togolese Republic", capitals: ["Lomé"], region: "Africa", categories: ["AU"] },
  { code: "TUN", name: "Tunisia", slug: "tunisia", officialName: "Republic of Tunisia", capitals: ["Tunis"], region: "Africa", categories: ["AU"] },
  { code: "UGA", name: "Uganda", slug: "uganda", officialName: "Republic of Uganda", capitals: ["Kampala"], region: "Africa", categories: ["AU"] },
  { code: "ZMB", name: "Zambia", slug: "zambia", officialName: "Republic of Zambia", capitals: ["Lusaka"], region: "Africa", categories: ["AU"] },
  { code: "ZWE", name: "Zimbabwe", slug: "zimbabwe", officialName: "Republic of Zimbabwe", capitals: ["Harare"], region: "Africa", categories: ["AU"] },
];
