export const countryCategories = [
  { id: "OECD", label: "OECD" },
  { id: "EU", label: "EU" },
  { id: "ASEAN", label: "ASEAN" },
  { id: "G20", label: "G20" },
  { id: "G7", label: "G7" },
  { id: "BRICS", label: "BRICS" },
  { id: "NATO", label: "NATO" },
  { id: "Eurozone", label: "Eurozone" },
];

export const countryRegions = [
  { id: "Asia", label: "Asia" },
  { id: "Europe", label: "Europe" },
  { id: "Oceania", label: "Oceania" },
  { id: "Africa", label: "Africa" },
  { id: "North America", label: "North America" },
  { id: "South America", label: "South America" },
];

// Search-only aliases live in countrySearchAliases.js.
export const countries = [
  { code: "USA", name: "United States", slug: "united-states", capitals: ["Washington D.C."], region: "North America", categories: ["G20", "G7", "NATO", "OECD"] },
  { code: "JPN", name: "Japan", slug: "japan", capitals: ["Tokyo"], region: "Asia", categories: ["G20", "G7", "OECD"] },
  { code: "CHN", name: "China", slug: "china", capitals: ["Beijing"], region: "Asia", categories: ["G20", "BRICS"] },
  { code: "TWN", name: "Taiwan", slug: "taiwan", capitals: ["Taipei"], region: "Asia", categories: [] },
  { code: "HKG", name: "Hong Kong", slug: "hong-kong", capitals: ["Hong Kong"], region: "Asia", categories: [] },
  { code: "MAC", name: "Macao", slug: "macao", capitals: ["Macao"], region: "Asia", categories: [] },
  { code: "DEU", name: "Germany", slug: "germany", capitals: ["Berlin"], region: "Europe", categories: ["G20", "EU", "NATO", "Eurozone", "G7", "OECD"] },
  { code: "FRA", name: "France", slug: "france", capitals: ["Paris"], region: "Europe", categories: ["G20", "EU", "NATO", "Eurozone", "G7", "OECD"] },
  { code: "GBR", name: "United Kingdom", slug: "united-kingdom", capitals: ["London"], region: "Europe", categories: ["G20", "G7", "NATO", "OECD"] },
  { code: "ITA", name: "Italy", slug: "italy", capitals: ["Rome"], region: "Europe", categories: ["G20", "EU", "NATO", "Eurozone", "G7", "OECD"] },
  { code: "CAN", name: "Canada", slug: "canada", capitals: ["Ottawa"], region: "North America", categories: ["G20", "G7", "NATO", "OECD"] },
  { code: "AUS", name: "Australia", slug: "australia", capitals: ["Canberra"], region: "Oceania", categories: ["G20", "OECD"] },
  { code: "NZL", name: "New Zealand", slug: "new-zealand", capitals: ["Wellington"], region: "Oceania", categories: ["OECD"] },
  { code: "ASM", name: "American Samoa", slug: "american-samoa", capitals: ["Pago Pago"], region: "Oceania", categories: [] },
  { code: "COK", name: "Cook Islands", slug: "cook-islands", capitals: ["Avarua"], region: "Oceania", categories: [] },
  { code: "FJI", name: "Fiji", slug: "fiji", capitals: ["Suva"], region: "Oceania", categories: [] },
  { code: "GUM", name: "Guam", slug: "guam", capitals: ["Hagåtña"], region: "Oceania", categories: [] },
  { code: "MNP", name: "Northern Mariana Islands", slug: "northern-mariana-islands", capitals: ["Saipan"], region: "Oceania", categories: [] },
  { code: "NCL", name: "New Caledonia", slug: "new-caledonia", capitals: ["Nouméa"], region: "Oceania", categories: [] },
  { code: "NIU", name: "Niue", slug: "niue", capitals: ["Alofi"], region: "Oceania", categories: [] },
  { code: "PCN", name: "Pitcairn", slug: "pitcairn", capitals: ["Adamstown"], region: "Oceania", categories: [] },
  { code: "PNG", name: "Papua New Guinea", slug: "papua-new-guinea", capitals: ["Port Moresby"], region: "Oceania", categories: [] },
  { code: "PYF", name: "French Polynesia", slug: "french-polynesia", capitals: ["Papeetē"], region: "Oceania", categories: [] },
  { code: "SLB", name: "Solomon Islands", slug: "solomon-islands", capitals: ["Honiara"], region: "Oceania", categories: [] },
  { code: "TKL", name: "Tokelau", slug: "tokelau", capitals: ["Nukunonu"], region: "Oceania", categories: [] },
  { code: "VUT", name: "Vanuatu", slug: "vanuatu", capitals: ["Port Vila"], region: "Oceania", categories: [] },
  { code: "FSM", name: "Federated States of Micronesia", slug: "federated-states-of-micronesia", capitals: ["Palikir"], region: "Oceania", categories: [] },
  { code: "KIR", name: "Kiribati", slug: "kiribati", capitals: ["South Tarawa"], region: "Oceania", categories: [] },
  { code: "MHL", name: "Marshall Islands", slug: "marshall-islands", capitals: ["Majuro"], region: "Oceania", categories: [] },
  { code: "NRU", name: "Nauru", slug: "nauru", capitals: ["Yaren"], region: "Oceania", categories: [] },
  { code: "PLW", name: "Palau", slug: "palau", capitals: ["Ngerulmud"], region: "Oceania", categories: [] },
  { code: "WSM", name: "Samoa", slug: "samoa", capitals: ["Apia"], region: "Oceania", categories: [] },
  { code: "TON", name: "Tonga", slug: "tonga", capitals: ["Nuku'alofa"], region: "Oceania", categories: [] },
  { code: "TUV", name: "Tuvalu", slug: "tuvalu", capitals: ["Funafuti"], region: "Oceania", categories: [] },
  { code: "WLF", name: "Wallis and Futuna", slug: "wallis-and-futuna", capitals: ["Mata-Utu"], region: "Oceania", categories: [] },
  { code: "KOR", name: "South Korea", slug: "south-korea", capitals: ["Seoul"], region: "Asia", categories: ["G20", "OECD"] },
  { code: "PRK", name: "North Korea", slug: "north-korea", capitals: ["Pyongyang"], region: "Asia", categories: [] },
  { code: "IDN", name: "Indonesia", slug: "indonesia", capitals: ["Jakarta"], region: "Asia", categories: ["G20", "ASEAN", "BRICS"] },
  { code: "TUR", name: "Türkiye", slug: "turkiye", capitals: ["Ankara"], region: "Asia", categories: ["G20", "NATO", "OECD"] },
  { code: "IND", name: "India", slug: "india", capitals: ["New Delhi"], region: "Asia", categories: ["G20", "BRICS"] },
  { code: "LKA", name: "Sri Lanka", slug: "sri-lanka", capitals: ["Sri Jayawardenepura Kotte", "Colombo"], region: "Asia", categories: [] },
  { code: "MDV", name: "Maldives", slug: "maldives", capitals: ["Malé"], region: "Asia", categories: [] },
  { code: "BGD", name: "Bangladesh", slug: "bangladesh", capitals: ["Dhaka"], region: "Asia", categories: [] },
  { code: "BTN", name: "Bhutan", slug: "bhutan", capitals: ["Thimphu"], region: "Asia", categories: [] },
  { code: "NPL", name: "Nepal", slug: "nepal", capitals: ["Kathmandu"], region: "Asia", categories: [] },
  { code: "PAK", name: "Pakistan", slug: "pakistan", capitals: ["Islamabad"], region: "Asia", categories: [] },
  { code: "AFG", name: "Afghanistan", slug: "afghanistan", capitals: ["Kabul"], region: "Asia", categories: [] },
  { code: "TJK", name: "Tajikistan", slug: "tajikistan", capitals: ["Dushanbe"], region: "Asia", categories: [] },
  { code: "KGZ", name: "Kyrgyzstan", slug: "kyrgyzstan", capitals: ["Bishkek"], region: "Asia", categories: [] },
  { code: "TKM", name: "Turkmenistan", slug: "turkmenistan", capitals: ["Ashgabat"], region: "Asia", categories: [] },
  { code: "UZB", name: "Uzbekistan", slug: "uzbekistan", capitals: ["Tashkent"], region: "Asia", categories: [] },
  { code: "KAZ", name: "Kazakhstan", slug: "kazakhstan", capitals: ["Astana"], region: "Asia", categories: [] },
  { code: "MNG", name: "Mongolia", slug: "mongolia", capitals: ["Ulaanbaatar"], region: "Asia", categories: [] },
  { code: "AZE", name: "Azerbaijan", slug: "azerbaijan", capitals: ["Baku"], region: "Asia", categories: [] },
  { code: "GEO", name: "Georgia", slug: "georgia", capitals: ["Tbilisi"], region: "Asia", categories: [] },
  { code: "ARM", name: "Armenia", slug: "armenia", capitals: ["Yerevan"], region: "Asia", categories: [] },
{ code: "SAU", name: "Saudi Arabia", slug: "saudi-arabia", capitals: ["Riyadh"], region: "Asia", categories: ["G20","BRICS"] },
  { code: "IRN", name: "Iran", slug: "iran", capitals: ["Tehran"], region: "Asia", categories: ["BRICS"] },
  { code: "IRQ", name: "Iraq", slug: "iraq", capitals: ["Baghdad"], region: "Asia", categories: [] },
  { code: "SYR", name: "Syria", slug: "syria", capitals: ["Damascus"], region: "Asia", categories: [] },
  { code: "LBN", name: "Lebanon", slug: "lebanon", capitals: ["Beirut"], region: "Asia", categories: [] },
  { code: "JOR", name: "Jordan", slug: "jordan", capitals: ["Amman"], region: "Asia", categories: [] },
  { code: "KWT", name: "Kuwait", slug: "kuwait", capitals: ["Kuwait City"], region: "Asia", categories: [] },
  { code: "BHR", name: "Bahrain", slug: "bahrain", capitals: ["Manama"], region: "Asia", categories: [] },
  { code: "QAT", name: "Qatar", slug: "qatar", capitals: ["Doha"], region: "Asia", categories: [] },
  { code: "ARE", name: "United Arab Emirates", slug: "united-arab-emirates", capitals: ["Abu Dhabi"], region: "Asia", categories: ["BRICS"] },
  { code: "OMN", name: "Oman", slug: "oman", capitals: ["Muscat"], region: "Asia", categories: [] },
  { code: "YEM", name: "Yemen", slug: "yemen", capitals: ["Sana'a"], region: "Asia", categories: [] },
  { code: "ARG", name: "Argentina", slug: "argentina", capitals: ["Buenos Aires"], region: "South America", categories: ["G20"] },
  { code: "BRA", name: "Brazil", slug: "brazil", capitals: ["Brasília"], region: "South America", categories: ["G20", "BRICS"] },
  { code: "MEX", name: "Mexico", slug: "mexico", capitals: ["Mexico City"], region: "North America", categories: ["G20", "OECD"] },
  { code: "ABW", name: "Aruba", slug: "aruba", capitals: ["Oranjestad"], region: "North America", categories: [] },
  { code: "AIA", name: "Anguilla", slug: "anguilla", capitals: ["The Valley"], region: "North America", categories: [] },
  { code: "BMU", name: "Bermuda", slug: "bermuda", capitals: ["Hamilton"], region: "North America", categories: ["NATO"] },
  { code: "GTM", name: "Guatemala", slug: "guatemala", capitals: ["Guatemala City"], region: "North America", categories: [] },
  { code: "BLZ", name: "Belize", slug: "belize", capitals: ["Belmopan"], region: "North America", categories: [] },
  { code: "SLV", name: "El Salvador", slug: "el-salvador", capitals: ["San Salvador"], region: "North America", categories: [] },
  { code: "HND", name: "Honduras", slug: "honduras", capitals: ["Tegucigalpa"], region: "North America", categories: [] },
  { code: "NIC", name: "Nicaragua", slug: "nicaragua", capitals: ["Managua"], region: "North America", categories: [] },
  { code: "PAN", name: "Panama", slug: "panama", capitals: ["Panama City"], region: "North America", categories: [] },
  { code: "BHS", name: "Bahamas", slug: "bahamas", capitals: ["Nassau"], region: "North America", categories: [] },
  { code: "CUB", name: "Cuba", slug: "cuba", capitals: ["Havana"], region: "North America", categories: [] },
  { code: "JAM", name: "Jamaica", slug: "jamaica", capitals: ["Kingston"], region: "North America", categories: [] },
  { code: "HTI", name: "Haiti", slug: "haiti", capitals: ["Port-au-Prince"], region: "North America", categories: [] },
  { code: "DOM", name: "Dominican Republic", slug: "dominican-republic", capitals: ["Santo Domingo"], region: "North America", categories: [] },
  { code: "ATG", name: "Antigua and Barbuda", slug: "antigua-and-barbuda", capitals: ["Saint John's"], region: "North America", categories: [] },
  { code: "KNA", name: "Saint Kitts and Nevis", slug: "saint-kitts-and-nevis", capitals: ["Basseterre"], region: "North America", categories: [] },
  { code: "DMA", name: "Dominica", slug: "dominica", capitals: ["Roseau"], region: "North America", categories: [] },
  { code: "LCA", name: "Saint Lucia", slug: "saint-lucia", capitals: ["Castries"], region: "North America", categories: [] },
  { code: "BRB", name: "Barbados", slug: "barbados", capitals: ["Bridgetown"], region: "North America", categories: [] },
  { code: "VCT", name: "Saint Vincent and the Grenadines", slug: "saint-vincent-and-the-grenadines", capitals: ["Kingstown"], region: "North America", categories: [] },
  { code: "GRD", name: "Grenada", slug: "grenada", capitals: ["St. George's"], region: "North America", categories: [] },
  { code: "TTO", name: "Trinidad and Tobago", slug: "trinidad-and-tobago", capitals: ["Port of Spain"], region: "North America", categories: [] },
  { code: "CYM", name: "Cayman Islands", slug: "cayman-islands", capitals: ["George Town"], region: "North America", categories: [] },
  { code: "CUW", name: "Curaçao", slug: "curacao", capitals: ["Willemstad"], region: "North America", categories: [] },
  { code: "GLP", name: "Guadeloupe", slug: "guadeloupe", capitals: ["Basse-Terre"], region: "North America", categories: ["EU", "Eurozone"] },
  { code: "GRL", name: "Greenland", slug: "greenland", capitals: ["Nuuk"], region: "North America", categories: ["NATO"] },
  { code: "MAF", name: "Saint Martin", slug: "saint-martin", capitals: ["Marigot"], region: "North America", categories: ["EU", "Eurozone"] },
  { code: "MSR", name: "Montserrat", slug: "montserrat", capitals: ["Brades"], region: "North America", categories: [] },
  { code: "MTQ", name: "Martinique", slug: "martinique", capitals: ["Fort-de-France"], region: "North America", categories: ["EU", "Eurozone"] },
  { code: "PRI", name: "Puerto Rico", slug: "puerto-rico", capitals: ["San Juan"], region: "North America", categories: [] },
  { code: "SPM", name: "Saint Pierre and Miquelon", slug: "saint-pierre-and-miquelon", capitals: ["Saint-Pierre"], region: "North America", categories: ["NATO", "Eurozone"] },
  { code: "SXM", name: "Sint Maarten", slug: "sint-maarten", capitals: ["Philipsburg"], region: "North America", categories: [] },
  { code: "TCA", name: "Turks and Caicos Islands", slug: "turks-and-caicos-islands", capitals: ["Cockburn Town"], region: "North America", categories: [] },
  { code: "VGB", name: "British Virgin Islands", slug: "british-virgin-islands", capitals: ["Road Town"], region: "North America", categories: [] },
  { code: "VIR", name: "U.S. Virgin Islands", slug: "us-virgin-islands", capitals: ["Charlotte Amalie"], region: "North America", categories: [] },
  { code: "VEN", name: "Venezuela", slug: "venezuela", capitals: ["Caracas"], region: "South America", categories: [] },
  { code: "FLK", name: "Falkland Islands", slug: "falkland-islands", capitals: ["Stanley"], region: "South America", categories: [] },
  { code: "GUF", name: "French Guiana", slug: "french-guiana", capitals: ["Cayenne"], region: "South America", categories: ["EU", "Eurozone"] },
  { code: "GUY", name: "Guyana", slug: "guyana", capitals: ["Georgetown"], region: "South America", categories: [] },
  { code: "SUR", name: "Suriname", slug: "suriname", capitals: ["Paramaribo"], region: "South America", categories: [] },
  { code: "ECU", name: "Ecuador", slug: "ecuador", capitals: ["Quito"], region: "South America", categories: [] },
  { code: "BOL", name: "Bolivia", slug: "bolivia", capitals: ["Sucre"], region: "South America", categories: [] },
  { code: "PRY", name: "Paraguay", slug: "paraguay", capitals: ["Asunción"], region: "South America", categories: [] },
  { code: "URY", name: "Uruguay", slug: "uruguay", capitals: ["Montevideo"], region: "South America", categories: [] },
  { code: "PER", name: "Peru", slug: "peru", capitals: ["Lima"], region: "South America", categories: [] },
  { code: "RUS", name: "Russia", slug: "russia", capitals: ["Moscow"], region: "Europe", categories: ["G20", "BRICS"] },
  { code: "ZAF", name: "South Africa", slug: "south-africa", capitals: ["Pretoria", "Cape Town", "Bloemfontein"], region: "Africa", categories: ["G20","BRICS"] },
  { code: "CHL", name: "Chile", slug: "chile", capitals: ["Santiago"], region: "South America", categories: ["OECD"] },
  { code: "COL", name: "Colombia", slug: "colombia", capitals: ["Bogotá"], region: "South America", categories: ["OECD"] },
  { code: "CRI", name: "Costa Rica", slug: "costa-rica", capitals: ["San José"], region: "North America", categories: ["OECD"] },
  { code: "NOR", name: "Norway", slug: "norway", capitals: ["Oslo"], region: "Europe", categories: ["NATO", "OECD"] },
  { code: "ISL", name: "Iceland", slug: "iceland", capitals: ["Reykjavik"], region: "Europe", categories: ["NATO", "OECD"] },
  { code: "CHE", name: "Switzerland", slug: "switzerland", capitals: ["Bern"], region: "Europe", categories: ["OECD"] },
  { code: "ISR", name: "Israel", slug: "israel", capitals: ["Jerusalem"], region: "Asia", categories: ["OECD"] },
  { code: "FRO", name: "Faroe Islands", slug: "faroe-islands", capitals: ["Tórshavn"], region: "Europe", categories: ["NATO"] },
  { code: "GIB", name: "Gibraltar", slug: "gibraltar", capitals: ["Gibraltar"], region: "Europe", categories: ["NATO"] },
  { code: "IMN", name: "Isle of Man", slug: "isle-of-man", capitals: ["Douglas"], region: "Europe", categories: ["NATO"] },
  { code: "LIE", name: "Liechtenstein", slug: "liechtenstein", capitals: ["Vaduz"], region: "Europe", categories: [] },
  { code: "VAT", name: "Vatican City", slug: "vatican-city", capitals: ["Vatican City"], region: "Europe", categories: [] },
  { code: "SMR", name: "San Marino", slug: "san-marino", capitals: ["City of San Marino"], region: "Europe", categories: [] },
  { code: "AND", name: "Andorra", slug: "andorra", capitals: ["Andorra la Vella"], region: "Europe", categories: [] },
  { code: "MCO", name: "Monaco", slug: "monaco", capitals: ["Monaco"], region: "Europe", categories: [] },
  { code: "BLR", name: "Belarus", slug: "belarus", capitals: ["Minsk"], region: "Europe", categories: [] },
  { code: "BIH", name: "Bosnia and Herzegovina", slug: "bosnia-and-herzegovina", capitals: ["Sarajevo"], region: "Europe", categories: [] },
  { code: "SRB", name: "Serbia", slug: "serbia", capitals: ["Belgrade"], region: "Europe", categories: [] },
  { code: "MNE", name: "Montenegro", slug: "montenegro", capitals: ["Podgorica"], region: "Europe", categories: ["NATO"] },
  { code: "KOS", name: "Kosovo", slug: "kosovo", capitals: ["Pristina"], region: "Europe", categories: [] },
  { code: "MKD", name: "North Macedonia", slug: "north-macedonia", capitals: ["Skopje"], region: "Europe", categories: ["NATO"] },
  { code: "ALB", name: "Albania", slug: "albania", capitals: ["Tirana"], region: "Europe", categories: ["NATO"] },
  { code: "MDA", name: "Moldova", slug: "moldova", capitals: ["Chișinău"], region: "Europe", categories: [] },
  { code: "UKR", name: "Ukraine", slug: "ukraine", capitals: ["Kyiv"], region: "Europe", categories: [] },
  { code: "AUT", name: "Austria", slug: "austria", capitals: ["Vienna"], region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "BEL", name: "Belgium", slug: "belgium", capitals: ["Brussels"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "BGR", name: "Bulgaria", slug: "bulgaria", capitals: ["Sofia"], region: "Europe", categories: ["EU", "NATO", "Eurozone"] },
  { code: "HRV", name: "Croatia", slug: "croatia", capitals: ["Zagreb"], region: "Europe", categories: ["EU", "NATO", "Eurozone"] },
  { code: "CYP", name: "Cyprus", slug: "cyprus", capitals: ["Nicosia"], region: "Asia", categories: ["EU", "Eurozone"] },
  { code: "CZE", name: "Czechia", slug: "czechia", capitals: ["Prague"], region: "Europe", categories: ["EU", "NATO", "OECD"] },
  { code: "DNK", name: "Denmark", slug: "denmark", capitals: ["Copenhagen"], region: "Europe", categories: ["EU", "NATO", "OECD"] },
  { code: "EST", name: "Estonia", slug: "estonia", capitals: ["Tallinn"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "FIN", name: "Finland", slug: "finland", capitals: ["Helsinki"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "GRC", name: "Greece", slug: "greece", capitals: ["Athens"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "HUN", name: "Hungary", slug: "hungary", capitals: ["Budapest"], region: "Europe", categories: ["EU", "NATO", "OECD"] },
  { code: "IRL", name: "Ireland", slug: "ireland", capitals: ["Dublin"], region: "Europe", categories: ["EU", "Eurozone", "OECD"] },
  { code: "LVA", name: "Latvia", slug: "latvia", capitals: ["Riga"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "LTU", name: "Lithuania", slug: "lithuania", capitals: ["Vilnius"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "LUX", name: "Luxembourg", slug: "luxembourg", capitals: ["Luxembourg"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "MLT", name: "Malta", slug: "malta", capitals: ["Valletta"], region: "Europe", categories: ["EU", "Eurozone"] },
  { code: "NLD", name: "Netherlands", slug: "netherlands", capitals: ["Amsterdam"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "POL", name: "Poland", slug: "poland", capitals: ["Warsaw"], region: "Europe", categories: ["EU", "NATO", "OECD"] },
  { code: "PRT", name: "Portugal", slug: "portugal", capitals: ["Lisbon"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "ROU", name: "Romania", slug: "romania", capitals: ["Bucharest"], region: "Europe", categories: ["EU", "NATO"] },
  { code: "SVK", name: "Slovakia", slug: "slovakia", capitals: ["Bratislava"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "SVN", name: "Slovenia", slug: "slovenia", capitals: ["Ljubljana"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "ESP", name: "Spain", slug: "spain", capitals: ["Madrid"], region: "Europe", categories: ["EU", "NATO", "Eurozone", "OECD"] },
  { code: "SWE", name: "Sweden", slug: "sweden", capitals: ["Stockholm"], region: "Europe", categories: ["EU", "NATO", "OECD"] },
  { code: "BRN", name: "Brunei", slug: "brunei", capitals: ["Bandar Seri Begawan"], region: "Asia", categories: ["ASEAN"] },
  { code: "KHM", name: "Cambodia", slug: "cambodia", capitals: ["Phnom Penh"], region: "Asia", categories: ["ASEAN"] },
  { code: "LAO", name: "Laos", slug: "laos", capitals: ["Vientiane"], region: "Asia", categories: ["ASEAN"] },
  { code: "MYS", name: "Malaysia", slug: "malaysia", capitals: ["Kuala Lumpur"], region: "Asia", categories: ["ASEAN"] },
  { code: "MMR", name: "Myanmar", slug: "myanmar", capitals: ["Naypyidaw"], region: "Asia", categories: ["ASEAN"] },
  { code: "PHL", name: "Philippines", slug: "philippines", capitals: ["Manila"], region: "Asia", categories: ["ASEAN"] },
  { code: "SGP", name: "Singapore", slug: "singapore", capitals: ["Singapore"], region: "Asia", categories: ["ASEAN"] },
  { code: "THA", name: "Thailand", slug: "thailand", capitals: ["Bangkok"], region: "Asia", categories: ["ASEAN"] },
  { code: "TLS", name: "Timor-Leste", slug: "timor-leste", capitals: ["Dili"], region: "Asia", categories: ["ASEAN"] },
  { code: "VNM", name: "Vietnam", slug: "vietnam", capitals: ["Hanoi"], region: "Asia", categories: ["ASEAN"] },
  { code: "WBG", name: "Palestine", slug: "palestine", capitals: ["Ramallah"], region: "Asia", categories: [] },
  { code: "DZA", name: "Algeria", slug: "algeria", capitals: ["Algiers"], region: "Africa", categories: [] },
  { code: "AGO", name: "Angola", slug: "angola", capitals: ["Luanda"], region: "Africa", categories: [] },
  { code: "BEN", name: "Benin", slug: "benin", capitals: ["Porto-Novo"], region: "Africa", categories: [] },
  { code: "BWA", name: "Botswana", slug: "botswana", capitals: ["Gaborone"], region: "Africa", categories: [] },
  { code: "BFA", name: "Burkina Faso", slug: "burkina-faso", capitals: ["Ouagadougou"], region: "Africa", categories: [] },
  { code: "BDI", name: "Burundi", slug: "burundi", capitals: ["Gitega"], region: "Africa", categories: [] },
  { code: "CPV", name: "Cabo Verde", slug: "cabo-verde", capitals: ["Praia"], region: "Africa", categories: [] },
  { code: "CMR", name: "Cameroon", slug: "cameroon", capitals: ["Yaoundé"], region: "Africa", categories: [] },
  { code: "CAF", name: "Central African Republic", slug: "central-african-republic", capitals: ["Bangui"], region: "Africa", categories: [] },
  { code: "TCD", name: "Chad", slug: "chad", capitals: ["N'Djamena"], region: "Africa", categories: [] },
  { code: "COM", name: "Comoros", slug: "comoros", capitals: ["Moroni"], region: "Africa", categories: [] },
  { code: "COG", name: "Republic of the Congo", slug: "republic-of-the-congo", capitals: ["Brazzaville"], region: "Africa", categories: [] },
  { code: "COD", name: "DR Congo", slug: "dr-congo", capitals: ["Kinshasa"], region: "Africa", categories: [] },
  { code: "CIV", name: "Côte d’Ivoire", slug: "cote-divoire", capitals: ["Yamoussoukro"], region: "Africa", categories: [] },
  { code: "DJI", name: "Djibouti", slug: "djibouti", capitals: ["Djibouti"], region: "Africa", categories: [] },
  { code: "EGY", name: "Egypt", slug: "egypt", capitals: ["Cairo"], region: "Africa", categories: ["BRICS"] },
  { code: "GNQ", name: "Equatorial Guinea", slug: "equatorial-guinea", capitals: ["Malabo"], region: "Africa", categories: [] },
  { code: "ERI", name: "Eritrea", slug: "eritrea", capitals: ["Asmara"], region: "Africa", categories: [] },
  { code: "SWZ", name: "Eswatini", slug: "eswatini", capitals: ["Mbabane", "Lobamba"], region: "Africa", categories: [] },
  { code: "ETH", name: "Ethiopia", slug: "ethiopia", capitals: ["Addis Ababa"], region: "Africa", categories: ["BRICS"] },
  { code: "GAB", name: "Gabon", slug: "gabon", capitals: ["Libreville"], region: "Africa", categories: [] },
  { code: "GMB", name: "Gambia", slug: "gambia", capitals: ["Banjul"], region: "Africa", categories: [] },
  { code: "GHA", name: "Ghana", slug: "ghana", capitals: ["Accra"], region: "Africa", categories: [] },
  { code: "GIN", name: "Guinea", slug: "guinea", capitals: ["Conakry"], region: "Africa", categories: [] },
  { code: "GNB", name: "Guinea-Bissau", slug: "guinea-bissau", capitals: ["Bissau"], region: "Africa", categories: [] },
  { code: "KEN", name: "Kenya", slug: "kenya", capitals: ["Nairobi"], region: "Africa", categories: [] },
  { code: "LSO", name: "Lesotho", slug: "lesotho", capitals: ["Maseru"], region: "Africa", categories: [] },
  { code: "LBR", name: "Liberia", slug: "liberia", capitals: ["Monrovia"], region: "Africa", categories: [] },
  { code: "LBY", name: "Libya", slug: "libya", capitals: ["Tripoli"], region: "Africa", categories: [] },
  { code: "MDG", name: "Madagascar", slug: "madagascar", capitals: ["Antananarivo"], region: "Africa", categories: [] },
  { code: "MWI", name: "Malawi", slug: "malawi", capitals: ["Lilongwe"], region: "Africa", categories: [] },
  { code: "MYT", name: "Mayotte", slug: "mayotte", capitals: ["Mamoudzou"], region: "Africa", categories: ["EU", "Eurozone"] },
  { code: "MLI", name: "Mali", slug: "mali", capitals: ["Bamako"], region: "Africa", categories: [] },
  { code: "MRT", name: "Mauritania", slug: "mauritania", capitals: ["Nouakchott"], region: "Africa", categories: [] },
  { code: "MUS", name: "Mauritius", slug: "mauritius", capitals: ["Port Louis"], region: "Africa", categories: [] },
  { code: "MAR", name: "Morocco", slug: "morocco", capitals: ["Rabat"], region: "Africa", categories: [] },
  { code: "MOZ", name: "Mozambique", slug: "mozambique", capitals: ["Maputo"], region: "Africa", categories: [] },
  { code: "NAM", name: "Namibia", slug: "namibia", capitals: ["Windhoek"], region: "Africa", categories: [] },
  { code: "NER", name: "Niger", slug: "niger", capitals: ["Niamey"], region: "Africa", categories: [] },
  { code: "NGA", name: "Nigeria", slug: "nigeria", capitals: ["Abuja"], region: "Africa", categories: [] },
  { code: "RWA", name: "Rwanda", slug: "rwanda", capitals: ["Kigali"], region: "Africa", categories: [] },
  { code: "REU", name: "Réunion", slug: "reunion", capitals: ["Saint-Denis"], region: "Africa", categories: ["EU", "Eurozone"] },
  { code: "SHN", name: "Saint Helena", slug: "saint-helena", capitals: ["Jamestown"], region: "Africa", categories: [] },
  { code: "STP", name: "São Tomé and Príncipe", slug: "sao-tome-and-principe", capitals: ["São Tomé"], region: "Africa", categories: [] },
  { code: "SEN", name: "Senegal", slug: "senegal", capitals: ["Dakar"], region: "Africa", categories: [] },
  { code: "SYC", name: "Seychelles", slug: "seychelles", capitals: ["Victoria"], region: "Africa", categories: [] },
  { code: "SLE", name: "Sierra Leone", slug: "sierra-leone", capitals: ["Freetown"], region: "Africa", categories: [] },
  { code: "SOM", name: "Somalia", slug: "somalia", capitals: ["Mogadishu"], region: "Africa", categories: [] },
  { code: "SSD", name: "South Sudan", slug: "south-sudan", capitals: ["Juba"], region: "Africa", categories: [] },
  { code: "SDN", name: "Sudan", slug: "sudan", capitals: ["Khartoum"], region: "Africa", categories: [] },
  { code: "TZA", name: "Tanzania", slug: "tanzania", capitals: ["Dodoma"], region: "Africa", categories: [] },
  { code: "TGO", name: "Togo", slug: "togo", capitals: ["Lomé"], region: "Africa", categories: [] },
  { code: "TUN", name: "Tunisia", slug: "tunisia", capitals: ["Tunis"], region: "Africa", categories: [] },
  { code: "UGA", name: "Uganda", slug: "uganda", capitals: ["Kampala"], region: "Africa", categories: [] },
  { code: "ZMB", name: "Zambia", slug: "zambia", capitals: ["Lusaka"], region: "Africa", categories: [] },
  { code: "ZWE", name: "Zimbabwe", slug: "zimbabwe", capitals: ["Harare"], region: "Africa", categories: [] },
];
