// Search-only country aliases and supplemental readings shared by every locale.
// Add spellings, readings, abbreviations, and common search variants here.
export const countrySearchAliases = {
  ARE: ["UAE", "VAE", "EAU", "BAE", "UEA"],
  AUS: ["오스트레일리아"],
  BLR: ["Weißrussland"],
  BRN: ["Brunei Darussalam", "Brunei Darüsselam", "브루나이다루살람", "ブルネイ・ダルサラーム国"],
  CAF: ["RCA", "Centrafrique"],
  CHN: ["PRC", "RRT", "People's Republic of China", "Volksrepublik China", "República Popular China", "République populaire de Chine", "República Popular da China", "Repubblica Popolare Cinese", "Çin ana karası", "Çin Halk Cumhuriyeti", "Tiongkok daratan", "Republik Rakyat Tiongkok", "중국 본토", "중화인민공화국", "中華人民共和国"],
  CIV: ["Ivory Coast", "Elfenbeinküste", "Costa Marfim"],
  COD: ["Democratic Republic of the Congo", "DRC", "RDC", "Congo-Kinshasa", "こんごみんしゅきょうわこく"],
  COG: ["Congo-Brazzaville"],
  CPV: ["Cape Verde", "Kapverden"],
  CZE: ["Czech Republic", "Tschechische Republik", "República Checa", "République tchèque", "República Tcheca", "Repubblica Ceca", "Çek Cumhuriyeti", "Republik Ceko", "체코공화국"],
  DEU: ["独"],
  FRA: ["仏"],
  FRO: ["Isole Faroe"],
  FSM: ["Mikronezya Federal Devletleri", "Negara Federasi Mikronesia"],
  GEO: ["グルジア"],
  GBR: ["UK", "England", "Great Britain", "Großbritannien", "Gran Bretaña", "Inglaterra", "Grande-Bretagne", "Angleterre", "Grã-Bretanha", "Gran Bretagna", "Inghilterra", "Büyük Britanya", "İngiltere", "Inggris", "그레이트브리튼", "英国", "英", "いんぐらんど", "イングランド"],
  IRN: ["Persia", "Persien", "ペルシャ"],
  JPN: ["にほん", "にっぽん", "日本国"],
  KOR: ["ROK", "Republic of Korea", "República de Corea", "République de Corée", "República da Coreia", "Repubblica di Corea", "Kore Cumhuriyeti", "Republik Korea", "Korsel", "대한민국", "남한", "かんこく", "大韓民国"],
  LKA: ["Ceylon", "セイロン"],
  MAC: ["Macau"],
  MDA: ["Moldawien"],
  MMR: ["Burma", "Birma", "Birmania", "ビルマ"],
  MNP: ["CNMI"],
  MYS: ["Malesia"],
  NLD: ["Holland", "Holanda", "Hollande", "홀란드"],
  NRU: ["Naoero", "ナオエロ"],
  PRK: ["DPRK", "RPDC", "Democratic People's Republic of Korea", "República Popular Democrática de Corea", "République populaire démocratique de Corée", "República Popular Democrática da Coreia", "Repubblica Popolare Democratica di Corea", "Kore Demokratik Halk Cumhuriyeti", "Republik Rakyat Demokratik Korea", "Korut", "조선민주주의인민공화국", "きたちょうせん", "朝鮮民主主義人民共和国"],
  RUS: ["Russian Federation", "Russische Föderation", "Federación de Rusia", "Federación Rusa", "Fédération de Russie", "Federação Russa", "Federazione Russa", "Rusya Federasyonu", "Federasi Rusia", "러시아연방", "ロシア連邦", "露"],
  SGP: ["Cingapura"],
  SWZ: ["Swaziland", "Swasiland", "Suazilandia", "スワジランド"],
  TLS: ["East Timor", "Osttimor", "티모르레스테"],
  TUR: ["Turkey", "Türkiye Cumhuriyeti"],
  TWN: ["ROC", "Republic of China", "República de China", "République de Chine", "República da China", "Repubblica di Cina", "Çin Cumhuriyeti", "Republik Tiongkok", "중화민국", "たいわん", "中華民国"],
  USA: ["EEUU", "Estados Unidos de América", "États-Unis d’Amérique", "Estados Unidos da América", "Stati Uniti d’America", "ABD", "AS", "미합중국", "米国", "米"],
  VAT: ["Holy See", "Santa Sede", "Kutsal Makam", "Takhta Suci", "교황청", "ローマ教皇庁"],
  WBG: ["West Bank and Gaza", "Estado de Palestina", "État de Palestine", "Estado da Palestina", "Stato di Palestina", "Filistin Devleti", "Negara Palestina", "Cisjordanie", "Cisjordânia", "Cisgiordania", "Batı Şeria", "Tepi Barat", "Bande de Gaza", "Faixa de Gaza", "Striscia di Gaza", "Gazze Şeridi", "Jalur Gaza", "Territoires palestiniens", "Territórios Palestinos", "Territori palestinesi", "Filistin Toprakları", "Wilayah Palestina", "팔레스타인국", "서안지구", "요르단강 서안", "가자지구", "ガザ", "ヨルダン川西岸"],
  ZAF: ["Güney Afrika Cumhuriyeti", "Republik Afrika Selatan", "남아공"],
};
