function defineDataSource(config) {
  return {
    ...config,
    ...(config.staticDataPath
      ? { rankingStaticDataPath: config.rankingStaticDataPath ?? config.staticDataPath.replace(/^\.\//, "../") }
      : {}),
  };
}

export const dataSources = {
  weoCurrentPrices: defineDataSource({
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    shortLabel: {
      en: "IMF WEO",
      ja: "IMF WEO",
    },
    staticDataPath: "./data/weo/current-prices.json",
    countryDataPath: "./data/weo/country-series/current-prices/{countryCode}.json",
    rankingStaticDataPath: "../data/weo/rankings/current-prices/manifest.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    subtitle: "IMF World Economic Outlook, 1980-2026",
  }),
  unctadTrade: defineDataSource({
    dataSource: "UNCTADstat",
    dataset: "UNCTAD Trade",
    shortLabel: {
      en: "UNCTAD",
      ja: "UNCTAD",
    },
    staticDataPath: "./data/unctad/trade.json",
    countryDataPath: "./data/unctad/country-series/trade/{countryCode}.json",
    rankingStaticDataPath: "../data/unctad/rankings/trade/manifest.json",
    sourceUrl: "https://unctadstat.unctad.org/datacentre/",
    startYear: 1948,
    endYear: 2025,
    subtitle: "UNCTADstat, 1948-2025",
  }),
  unctadServicesTrade: defineDataSource({
    dataSource: "UNCTADstat",
    dataset: "UNCTAD Services Trade",
    shortLabel: {
      en: "UNCTAD",
      ja: "UNCTAD",
    },
    staticDataPath: "./data/unctad/services-trade.json",
    countryDataPath: "./data/unctad/country-series/services-trade/{countryCode}.json",
    rankingStaticDataPath: "../data/unctad/rankings/services-trade/manifest.json",
    sourceUrl: "https://unctadstat.unctad.org/datacentre/",
    startYear: 2005,
    endYear: 2024,
    subtitle: "UNCTADstat, 2005-2024",
  }),
  worldBankWdi: defineDataSource({
    dataSource: "World Bank",
    dataset: "World Development Indicators",
    shortLabel: {
      en: "WB",
      ja: "世銀",
    },
    staticDataPath: "./data/world-bank/total-reserves.json",
    countryDataPath: "./data/world-bank/country-series/total-reserves/{countryCode}.json",
    rankingStaticDataPath: "../data/world-bank/rankings/total-reserves/manifest.json",
    sourceUrl: "https://data.worldbank.org/indicator/FI.RES.TOTL.CD",
    aboutSourceId: "world-bank-wdi",
    aboutSourceUrl: "https://databank.worldbank.org/source/world-development-indicators",
    startYear: 1960,
    endYear: 2024,
    subtitle: "World Bank World Development Indicators, 1960-2024",
  }),
  unWppPopulation: defineDataSource({
    dataSource: "United Nations",
    dataset: "World Population Prospects",
    shortLabel: {
      en: "UNWPP",
      ja: "UNWPP",
    },
    staticDataPath: "./data/un-wpp/population.json",
    countryDataPath: "./data/un-wpp/country-series/population/{countryCode}.json",
    rankingStaticDataPath: "../data/un-wpp/rankings/population/manifest.json",
    sourceUrl: "https://population.un.org/wpp/downloads",
    startYear: 1950,
    endYear: 2026,
    subtitle: "UN World Population Prospects, 1950-2026",
    observationStatusHighlightStatuses: ["projected"],
  }),
  unMigrantStock: defineDataSource({
    dataSource: "UN DESA Population Division",
    dataset: "International Migrant Stock",
    shortLabel: {
      en: "UN DESA",
      ja: "UN DESA",
    },
    staticDataPath: "./data/un-migrant-stock/immigrants.json",
    countryDataPath: "./data/un-migrant-stock/country-series/immigrants/{countryCode}.json",
    rankingStaticDataPath: "../data/un-migrant-stock/rankings/immigrants/manifest.json",
    sourceUrl: "https://www.un.org/development/desa/pd/content/international-migrant-stock",
    startYear: 1990,
    endYear: 2024,
    subtitle: "UN DESA International Migrant Stock, 1990-2024",
  }),
  worldBankEnvironment: defineDataSource({
    dataSource: "World Bank",
    dataset: "World Development Indicators",
    shortLabel: {
      en: "WB",
      ja: "世銀",
    },
    staticDataPath: "./data/world-bank/environment.json",
    countryDataPath: "./data/world-bank/country-series/environment/{countryCode}.json",
    rankingStaticDataPath: "../data/world-bank/rankings/environment/manifest.json",
    sourceUrl: "https://databank.worldbank.org/source/world-development-indicators",
    aboutSourceId: "world-bank-wdi",
    startYear: 1970,
    endYear: 2024,
    subtitle: "World Bank World Development Indicators, 1970-2024",
  }),
  unNationalAccountsGni: defineDataSource({
    dataSource: "UNdata",
    dataset: "National Accounts Main Aggregates Database",
    shortLabel: {
      en: "UNdata",
      ja: "UNdata",
    },
    staticDataPath: "./data/un-national-accounts/gni.json",
    countryDataPath: "./data/un-national-accounts/country-series/gni/{countryCode}.json",
    rankingStaticDataPath: "../data/un-national-accounts/rankings/gni/manifest.json",
    sourceUrl: "https://data.un.org/Explorer.aspx?d=SNAAMA",
    startYear: 1970,
    endYear: 2024,
    subtitle: "UNdata National Accounts Main Aggregates Database, 1970-2024",
  }),
  ciaWorldFactbook: defineDataSource({
    dataSource: "CIA",
    dataset: "The World Factbook",
    shortLabel: {
      en: "CIA",
      ja: "CIA",
    },
    staticDataPath: "./data/cia/area.json",
    rankingStaticDataPath: "../data/cia/rankings/area/manifest.json",
    sourceUrl: "https://www.cia.gov/the-world-factbook/",
    startYear: 2025,
    endYear: 2025,
    subtitle: "CIA World Factbook, 2025",
  }),
  sipriMilitarySpending: defineDataSource({
    dataSource: "SIPRI Military Expenditure Database",
    dataset: "SIPRI Military Spending",
    shortLabel: {
      en: "SIPRI",
      ja: "SIPRI",
    },
    staticDataPath: "./data/sipri/military-spending.json",
    countryDataPath: "./data/sipri/country-series/military-spending/{countryCode}.json",
    rankingStaticDataPath: "../data/sipri/rankings/military-spending/manifest.json",
    sourceUrl: "https://www.sipri.org/databases/milex",
    startYear: 1949,
    endYear: 2025,
    subtitle: "SIPRI Military Expenditure Database, 1949-2025",
  }),
  undpHdi: defineDataSource({
    dataSource: "UNDP Human Development Reports",
    dataset: "Human Development Index",
    shortLabel: {
      en: "UNDP",
      ja: "UNDP",
    },
    staticDataPath: "./data/undp/hdi.json",
    countryDataPath: "./data/undp/country-series/hdi/{countryCode}.json",
    rankingStaticDataPath: "../data/undp/rankings/hdi/manifest.json",
    sourceUrl: "https://hdr.undp.org/data-center/documentation-and-downloads",
    startYear: 1990,
    endYear: 2023,
    subtitle: "UNDP Human Development Reports, 1990-2023",
  }),
  unNationalAccountsEstimates: defineDataSource({
    dataSource: "UNdata",
    dataset: "National Accounts Estimates of Main Aggregates",
    shortLabel: {
      en: "UNdata",
      ja: "UNdata",
    },
    sourceUrl: "https://data.un.org/Explorer.aspx?d=SNAAMA",
    aboutOnly: true,
  }),
  unComtrade: defineDataSource({
    dataSource: "UN Comtrade",
    dataset: "UN Comtrade Database",
    shortLabel: {
      en: "UN Comtrade",
      ja: "UN Comtrade",
    },
    sourceUrl: "https://comtrade.un.org/",
    aboutOnly: true,
  }),
  oecdRevenueStatistics: defineDataSource({
    dataSource: "OECD",
    dataset: "Global Revenue Statistics Database",
    shortLabel: {
      en: "OECD",
      ja: "OECD",
    },
    sourceUrl: "https://data-explorer.oecd.org/",
    aboutOnly: true,
  }),
};
