function defineDataSource(config) {
  return {
    ...config,
    ...(config.staticDataPath
      ? { rankingStaticDataPath: config.rankingStaticDataPath ?? config.staticDataPath.replace(/^\.\//, "../") }
      : {}),
  };
}

export const dataSources = {
  weoCurrentPrices: defineDataSource({
    dataSource: "IMF World Economic Outlook",
    dataset: "WEO",
    citationLabel: "IMF World Economic Outlook",
    shortLabel: {
      en: "IMF WEO",
      ja: "IMF WEO",
      es: "FMI WEO",
      fr: "FMI WEO",
      pt: "FMI WEO",
      de: "IWF WEO",
      it: "FMI WEO",
      ko: "IMF WEO",
      tr: "IMF WEO",
      id: "IMF WEO",
    },
    staticDataPath: "./data/weo/current-prices.json",
    countryDataPath: "./data/weo/country-series/current-prices/{countryCode}.json",
    rankingStaticDataPath: "../data/weo/rankings/current-prices/manifest.json",
    sourceUrl: "https://data.imf.org/-/media/iData/External-Storage/Documents/2F78EE59F79143A7921E5E203D3AAA80/en/WEOApr2026all.xlsx",
    startYear: 1980,
    endYear: 2026,
    subtitle: "IMF World Economic Outlook, 1980-2026",
  }),
  unctadTrade: defineDataSource({
    dataSource: "UNCTADstat",
    dataset: "UNCTAD Trade",
    citationLabel: "UNCTADstat",
    aboutSourceId: "unctadstat",
    aboutSourceUrl: "https://unctadstat.unctad.org/datacentre/",
    shortLabel: {
      en: "UNCTAD",
      ja: "UNCTAD",
      es: "UNCTAD",
      fr: "CNUCED",
      pt: "UNCTAD",
      de: "UNCTAD",
      it: "UNCTAD",
      ko: "UNCTAD",
      tr: "UNCTAD",
      id: "UNCTAD",
    },
    staticDataPath: "./data/unctad/trade.json",
    countryDataPath: "./data/unctad/country-series/trade/{countryCode}.json",
    rankingStaticDataPath: "../data/unctad/rankings/trade/manifest.json",
    sourceUrl: "https://unctadstat.unctad.org/datacentre/",
    startYear: 1948,
    endYear: 2025,
    subtitle: "UNCTADstat, 1948-2025",
  }),
  unctadServicesTrade: defineDataSource({
    dataSource: "UNCTADstat",
    dataset: "UNCTAD Services Trade",
    citationLabel: "UNCTADstat",
    aboutSourceId: "unctadstat",
    aboutSourceUrl: "https://unctadstat.unctad.org/datacentre/",
    shortLabel: {
      en: "UNCTAD",
      ja: "UNCTAD",
      es: "UNCTAD",
      fr: "CNUCED",
      pt: "UNCTAD",
      de: "UNCTAD",
      it: "UNCTAD",
      ko: "UNCTAD",
      tr: "UNCTAD",
      id: "UNCTAD",
    },
    staticDataPath: "./data/unctad/services-trade.json",
    countryDataPath: "./data/unctad/country-series/services-trade/{countryCode}.json",
    rankingStaticDataPath: "../data/unctad/rankings/services-trade/manifest.json",
    sourceUrl: "https://unctadstat.unctad.org/datacentre/",
    startYear: 2005,
    endYear: 2024,
    subtitle: "UNCTADstat, 2005-2024",
  }),
  worldBankWdi: defineDataSource({
    dataSource: "World Bank",
    dataset: "World Development Indicators",
    citationLabel: "World Bank World Development Indicators",
    shortLabel: {
      en: "WB",
      ja: "世銀",
      es: "BM",
      fr: "BM",
      pt: "BM",
      de: "Weltbank",
      it: "Banca mondiale",
      ko: "세계은행",
      tr: "Dünya Bankası",
      id: "Bank Dunia",
    },
    staticDataPath: "./data/world-bank/total-reserves.json",
    countryDataPath: "./data/world-bank/country-series/total-reserves/{countryCode}.json",
    rankingStaticDataPath: "../data/world-bank/rankings/total-reserves/manifest.json",
    sourceUrl: "https://data.worldbank.org/indicator/FI.RES.TOTL.CD",
    aboutSourceId: "world-bank-wdi",
    aboutSourceUrl: "https://databank.worldbank.org/source/world-development-indicators",
    startYear: 1960,
    endYear: 2024,
    subtitle: "World Bank World Development Indicators, 1960-2024",
  }),
  unWppPopulation: defineDataSource({
    dataSource: "United Nations",
    dataset: "World Population Prospects",
    citationLabel: "UN World Population Prospects",
    shortLabel: {
      en: "UNWPP",
      ja: "UNWPP",
      es: "UNWPP",
      fr: "ONU WPP",
      pt: "ONU WPP",
      de: "UN WPP",
      it: "ONU WPP",
      ko: "UN WPP",
      tr: "UN WPP",
      id: "UN WPP",
    },
    staticDataPath: "./data/un-wpp/population.json",
    countryDataPath: "./data/un-wpp/country-series/population/{countryCode}.json",
    rankingStaticDataPath: "../data/un-wpp/rankings/population/manifest.json",
    sourceUrl: "https://population.un.org/wpp/downloads",
    startYear: 1950,
    endYear: 2026,
    subtitle: "UN World Population Prospects, 1950-2026",
    observationStatusHighlightStatuses: ["projected"],
  }),
  unMigrantStock: defineDataSource({
    dataSource: "UN DESA Population Division",
    dataset: "International Migrant Stock",
    citationLabel: "UN DESA International Migrant Stock",
    shortLabel: {
      en: "UN DESA",
      ja: "UN DESA",
      es: "ONU DAES",
      fr: "ONU DAES",
      pt: "ONU DESA",
      de: "UN DESA",
      it: "ONU DESA",
      ko: "UN DESA",
      tr: "BM DESA",
      id: "UN DESA",
    },
    staticDataPath: "./data/un-migrant-stock/immigrants.json",
    countryDataPath: "./data/un-migrant-stock/country-series/immigrants/{countryCode}.json",
    rankingStaticDataPath: "../data/un-migrant-stock/rankings/immigrants/manifest.json",
    sourceUrl: "https://www.un.org/development/desa/pd/content/international-migrant-stock",
    startYear: 1990,
    endYear: 2024,
    subtitle: "UN DESA International Migrant Stock, 1990-2024",
  }),
  worldBankEnvironment: defineDataSource({
    dataSource: "World Bank",
    dataset: "World Development Indicators",
    citationLabel: "World Bank World Development Indicators",
    shortLabel: {
      en: "WB",
      ja: "世銀",
      es: "BM",
      fr: "BM",
      pt: "BM",
      de: "Weltbank",
      it: "Banca mondiale",
      ko: "세계은행",
      tr: "Dünya Bankası",
      id: "Bank Dunia",
    },
    staticDataPath: "./data/world-bank/environment.json",
    countryDataPath: "./data/world-bank/country-series/environment/{countryCode}.json",
    rankingStaticDataPath: "../data/world-bank/rankings/environment/manifest.json",
    sourceUrl: "https://databank.worldbank.org/source/world-development-indicators",
    aboutSourceId: "world-bank-wdi",
    startYear: 1970,
    endYear: 2024,
    subtitle: "World Bank World Development Indicators, 1970-2024",
  }),
  unNationalAccountsGni: defineDataSource({
    dataSource: "UNdata",
    dataset: "National Accounts Main Aggregates Database",
    citationLabel: "UNdata National Accounts Main Aggregates Database",
    shortLabel: {
      en: "UNdata",
      ja: "UNdata",
      es: "UNdata",
      fr: "UNdata",
      pt: "UNdata",
      de: "UNdata",
      it: "UNdata",
      ko: "UNdata",
      tr: "UNdata",
      id: "UNdata",
    },
    staticDataPath: "./data/un-national-accounts/gni.json",
    countryDataPath: "./data/un-national-accounts/country-series/gni/{countryCode}.json",
    rankingStaticDataPath: "../data/un-national-accounts/rankings/gni/manifest.json",
    sourceUrl: "https://data.un.org/Explorer.aspx?d=SNAAMA",
    aboutSourceId: "undata",
    aboutSourceLabel: "UNdata",
    aboutSourceUrl: "https://data.un.org/",
    startYear: 1970,
    endYear: 2024,
    subtitle: "UNdata National Accounts Main Aggregates Database, 1970-2024",
  }),
  undataArea: defineDataSource({
    dataSource: "UNdata",
    dataset: "Country Profiles",
    citationLabel: "UNdata",
    shortLabel: {
      en: "UNdata",
      ja: "UNdata",
      es: "UNdata",
      fr: "UNdata",
      pt: "UNdata",
      de: "UNdata",
      it: "UNdata",
      ko: "UNdata",
      tr: "UNdata",
      id: "UNdata",
    },
    staticDataPath: "./data/undata/area.json",
    rankingStaticDataPath: "../data/undata/rankings/area/manifest.json",
    sourceUrl: "https://data.un.org/",
    aboutSourceId: "undata",
    aboutSourceLabel: "UNdata",
    aboutSourceUrl: "https://data.un.org/",
    startYear: 2023,
    endYear: 2023,
    subtitle: "UNdata, 2023",
  }),
  worldBankMilitarySpending: defineDataSource({
    dataSource: "World Bank",
    dataset: "World Development Indicators",
    citationLabel: "World Bank World Development Indicators",
    shortLabel: {
      en: "WB",
      ja: "世銀",
      es: "BM",
      fr: "BM",
      pt: "BM",
      de: "Weltbank",
      it: "Banca mondiale",
      ko: "세계은행",
      tr: "Dünya Bankası",
      id: "Bank Dunia",
    },
    staticDataPath: "./data/world-bank/military-spending.json",
    countryDataPath: "./data/world-bank/country-series/military-spending/{countryCode}.json",
    rankingStaticDataPath: "../data/world-bank/rankings/military-spending/manifest.json",
    sourceUrl: "https://data.worldbank.org/indicator/MS.MIL.XPND.CD",
    aboutSourceId: "world-bank-wdi",
    aboutSourceUrl: "https://databank.worldbank.org/source/world-development-indicators",
    startYear: 1960,
    endYear: 2024,
    subtitle: "World Bank World Development Indicators, 1960-2024",
  }),
  undpHdi: defineDataSource({
    dataSource: "UNDP Human Development Reports",
    dataset: "Human Development Index",
    citationLabel: "UNDP Human Development Reports",
    shortLabel: {
      en: "UNDP",
      ja: "UNDP",
      es: "PNUD",
      fr: "PNUD",
      pt: "PNUD",
      de: "UNDP",
      it: "UNDP",
      ko: "UNDP",
      tr: "UNDP",
      id: "UNDP",
    },
    staticDataPath: "./data/undp/hdi.json",
    countryDataPath: "./data/undp/country-series/hdi/{countryCode}.json",
    rankingStaticDataPath: "../data/undp/rankings/hdi/manifest.json",
    sourceUrl: "https://hdr.undp.org/data-center/documentation-and-downloads",
    startYear: 1990,
    endYear: 2023,
    subtitle: "UNDP Human Development Reports, 1990-2023",
  }),
};
