export const tradeRankings = [
  {
    seriesId: "tradeBalance",
    directory: "trade-balance",
    label: "Trade Balance",
    countryPageKind: "trade",
    countryPageLabel: "Trade Balance",
    relatedIndicatorLabel: "Trade Balance",
    section: "Trade Balance",
  },
  {
    seriesId: "exports",
    directory: "exports",
    label: "Exports",
    countryPageKind: "trade",
    countryPageLabel: "Trade",
    section: "Trade Balance",
  },
  {
    seriesId: "imports",
    directory: "imports",
    label: "Imports",
    countryPageKind: "trade",
    countryPageLabel: "Trade",
    section: "Trade Balance",
  },
  {
    seriesId: "servicesTradeBalance",
    directory: "services-trade-balance",
    label: "Services Trade Balance",
    countryPageKind: "services-trade",
    countryPageLabel: "Services Trade",
    relatedIndicatorLabel: "Services Trade Balance",
    section: "Services Trade Balance",
  },
  {
    seriesId: "servicesExports",
    directory: "services-exports",
    label: "Services Exports",
    countryPageKind: "services-trade",
    countryPageLabel: "Services Trade",
    section: "Services Trade Balance",
  },
  {
    seriesId: "servicesImports",
    directory: "services-imports",
    label: "Services Imports",
    countryPageKind: "services-trade",
    countryPageLabel: "Services Trade",
    section: "Services Trade Balance",
  },
  {
    seriesId: "currentAccountBalance",
    directory: "current-account-balance",
    label: "Current Account Balance",
    countryPageKind: "current-account-balance",
    section: "Current Account",
  },
  {
    seriesId: "currentAccountBalancePercentGdp",
    directory: "current-account-balance-percent-gdp",
    label: "Current Account Balance (% of GDP)",
    countryPageKind: "current-account-balance",
    section: "Current Account",
  },
];
